### PR TITLE
Update Inazuma Eleven 3 The Ogre EUR

### PR DESCRIPTION
**Pull request by Quack98**
Wanted this cheat and is one of the greatest so i would like to request it

### CODE REVIEW

**Review by Quack98 — COMMENTED** [review]
please put this cheat in the plugin

**Comment by Xantiii** [comment]
What does it do?

**Comment by Quack98** [comment]
that cheat can modify the moves that originally cant be changed

**Comment by Xantiii** [comment]
Interesting, so I agree

**Comment by Quack98** [comment]
great

**Comment by Quack98** [comment]
so now if i download the plugin this cheat will be in it?
if you diddnt put it in the plugin, can you do it please?

**Pull request merged**
